services:
    payplug.payment:
        class: Alcalyn\PayplugBundle\Services\PayplugPaymentService
        arguments:
            - %payplug.account.url%
            - %payplug.account.yourPrivateKey%
            - %payplug.sandbox.account.url%
            - %payplug.sandbox.account.yourPrivateKey%
            - %payplug.sandbox.enabled%
            - @router
        
    payplug.ipn:
        class: Alcalyn\PayplugBundle\Services\PayplugIPNService
        arguments: [%payplug.account.payplugPublicKey%, %payplug.class.ipn%]
        
    payplug.account_loader:
        class: Alcalyn\PayplugBundle\Services\PayplugAccountLoader
        arguments: [%kernel.root_dir%]

    payplug.command.account_loader:
        class: Alcalyn\PayplugBundle\Command\AccountLoaderCommand
        arguments: [@payplug.account_loader]
        tags:
            -  { name: console.command }

    payplug.command.generate_url:
        class: Alcalyn\PayplugBundle\Command\GenerateUrlCommand
        arguments: [@payplug.payment]
        tags:
            -  { name: console.command }
