services:
    payplug.payment:
        class: Alcalyn\PayplugBundle\Services\PayplugPaymentService
        arguments:
            - %payplug.account.url%
            - %payplug.account.yourPrivateKey%
            - %payplug.sandbox.account.url%
            - %payplug.sandbox.account.yourPrivateKey%
            - %payplug.sandbox.enabled%
        calls:
            - [setIpnUrlFromRouter, ["@router"]]
        
    payplug.ipn:
        class: Alcalyn\PayplugBundle\Services\PayplugIPNService
        arguments: [%payplug.account.payplugPublicKey%, %payplug.class.ipn%]
        
    payplug.account_loader:
        class: Alcalyn\PayplugBundle\Services\PayplugAccountLoader
        arguments: [%kernel.root_dir%]
